### ISSUE TITLE
SteamKit

### ISSUE THREAD

**Issue by LeonSK** [STRATZ-Ken/ccminer#1]
"The issue with the expiration is, if you call LogOff at any point, all your tokens are now invalid. However, if you call a Disconnect, you can reconnect using the same token. Thanks, all is working now. Though, I completely removed the Polling and made my own method as it was not dynamic enough to support everything I needed."

Could you help me to provide your code ? I have the same issue.

**Comment by STRATZ-Ken** [comment]
Just dont call log off ever.

**Comment by LeonSK** [comment]
Thx but i mean more about your "own method as it was not dynamic enough to support everything I needed" . Can provide me your own method?

**Comment by STRATZ-Ken** [comment]
Oh, I just took the code out of SteamKit for the login process.  The entire polling portion, I looked at the source code, and took it all out piece by piece so my login could handle the way I needed.

**Comment by LeonSK** [comment]
Thank you. Really help me .
